# -*- coding: utf-8 -*-
"""interp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dkhvxd51EZc_onNpJZ8FIJIrWY3A2TFC
"""

import numpy as np
import pandas as pd

wl = [i for i in range(700, 900)]
file_list = [
    'Salomatina2006.csv'
]

for i, fid in enumerate(file_list):
    fin = pd.read_csv(fid)
    mua = np.interp(wl, fin['wl'], fin['musp'])
    mua = mua*10
    fout = pd.DataFrame({'wl':wl, 'musp': mua})
    fout.to_csv(f'out_{fid}', index=False)
    print(f'File {i:<4} done !')
